version: "3.8"
services:
  photoprism:
    image: photoprism/photoprism:latest
    ports:
      - "2342:2342"
    environment:
      - PHOTOPRISM_ADMIN_PASSWORD=${PHOTOPRISM_ADMIN_PASSWORD}
      - PHOTOPRISM_HTTP_PORT=2342
      - PHOTOPRISM_SITE_URL=http://localhost:2342/
      - PHOTOPRISM_WORKERS=2
      - PHOTOPRISM_DISABLE_WEBDAV=true
      - PHOTOPRISM_ORIGINALS_PATH=/photoprism/originals
      - PHOTOPRISM_STORAGE_PATH=/photoprism/storage
      - PHOTOPRISM_VISION_URL=http://vision:5000
    volumes:
      - C:\Ideas\SearchMyFiles\llm-stack\data\photoprism\originals:/photoprism/originals
      - C:\Ideas\SearchMyFiles\llm-stack\data\photoprism\storage:/photoprism/storage
    restart: unless-stopped
    container_name: photoprism

  vision:
    image: photoprism/vision:latest
    environment:
      - VISION_HTTP_PORT=5000
      - HF_HOME=/cache/hf
    ports:
      - "2343:5000"
    volumes:
      - C:\Ideas\SearchMyFiles\llm-stack\data\photoprism\vision-models:/app/models
      - C:\Ideas\SearchMyFiles\llm-stack\data\photoprism\vision-cache:/cache/hf
    restart: unless-stopped
    container_name: photoprism-vision
